name: Vue CI

on:
  push:
    branches:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build Aepp
        run: yarn build
      # not working currently
      # - run: npx cypress install
      # - run: yarn test:e2e
      # - run: yarn test:unit
